### ISSUE TITLE
[功能请求]希望可以管理证书

### ISSUE THREAD

**Issue by tdjnodj** [taffychan/naiveproxy#1]
您的别的项目中都可以管理证书，但这个脚本没有，对您来说应该很容易实现这种功能，谢谢了🙏。

另外，您的x-ui项目中ss2022的链接不是base64编码的，部分客户端无法识别。经测试，普通ss的链接就是编码过的，但就ss2022不行。

**Comment by taffychan** [comment]
1. 关于SS2022问题，可以反馈是什么客户端吗？
2. 这个脚本我默认使用的是Acme的证书，可以使用我的Acme脚本来管理。

**Comment by tdjnodj** [comment]
> 
客户端:Qv2Ray
例:加密方式:2022-blake3-chacha20-poly1305，密码:M3R4OXR5NmcycEVZYlNWT09KdDU4RHBxMUw0aVhISTE=，服务器:1.1.1.1,端口：10086
正常的链接格式:ss://method:password@server:port 然后对后面进行base64处理。
所以上面的例子应该变成:
ss://MjAyMi1ibGFrZTMtY2hhY2hhMjAtcG9seTEzMDU6TTNSNE9YUjVObWN5Y0VWWllsTldUMDlLZERVNFJIQnhNVXcwYVZoSVNURT1AMS4xLjEuMToxMDA4Ng==
但面板生成的却是:
ss://2022-blake3-chacha20-poly1305:M3R4OXR5NmcycEVZYlNWT09KdDU4RHBxMUw0aVhISTE=@1.1.1.1:10086
就是"ss://"后面的内容没有经过base64处理，而经测试，面板生成的原始加密方式生成的链接格式后面是经过处理的。
而且原作有个遗留问题：ss加上http伪装后生成的链接数据不带伪装参数，希望这个问题也能解决。

**Comment by tdjnodj** [comment]
> 1. 关于SS2022的问题，可以反馈是什么客户端吗？
> 2. 这个脚本我默认使用的是 Acme 的证书，可以使用我的 Acme 脚本来管理。

客户端:Qv2Ray
例:加密方式:2022-blake3-chacha20-poly1305，密码:M3R4OXR5NmcycEVZYlNWT09KdDU4RHBxMUw0aVhISTE=，服务器:1.1.1.1,端口：10086
正常的链接格式:ss://method:password@server:port 然后对后面进行base64处理。
所以上面的例子应该变成:
ss://MjAyMi1ibGFrZTMtY2hhY2hhMjAtcG9seTEzMDU6TTNSNE9YUjVObWN5Y0VWWllsTldUMDlLZERVNFJIQnhNVXcwYVZoSVNURT1AMS4xLjEuMToxMDA4Ng==
但面板生成的却是:
ss://2022-blake3-chacha20-poly1305:M3R4OXR5NmcycEVZYlNWT09KdDU4RHBxMUw0aVhISTE=@1.1.1.1:10086
就是"ss://"后面的内容没有经过base64处理，而经测试，面板生成的原始加密方式生成的链接格式后面是经过处理的。
而且原作有个遗留问题：ss加上http伪装后生成的链接数据不带伪装参数，希望这个问题也能解决。

**Comment by taffychan** [comment]
> > 1. 关于SS2022的问题，可以反馈是什么客户端吗？
> > 2. 这个脚本我默认使用的是 Acme 的证书，可以使用我的 Acme 脚本来管理。
> 
> 客户端:Qv2Ray 例:加密方式:2022-blake3-chacha20-poly1305，密码:M3R4OXR5NmcycEVZYlNWT09KdDU4RHBxMUw0aVhISTE=，服务器:1.1.1.1,端口：10086 正常的链接格式:ss://method:password@server:port 然后对后面进行base64处理。 所以上面的例子应该变成: ss://MjAyMi1ibGFrZTMtY2hhY2hhMjAtcG9seTEzMDU6TTNSNE9YUjVObWN5Y0VWWllsTldUMDlLZERVNFJIQnhNVXcwYVZoSVNURT1AMS4xLjEuMToxMDA4Ng== 但面板生成的却是: ss://2022-blake3-chacha20-poly1305:M3R4OXR5NmcycEVZYlNWT09KdDU4RHBxMUw0aVhISTE=@1.1.1.1:10086 就是"ss://"后面的内容没有经过base64处理，而经测试，面板生成的原始加密方式生成的链接格式后面是经过处理的。 而且原作有个遗留问题：ss加上http伪装后生成的链接数据不带伪装参数，希望这个问题也能解决。

ss2022的链接我是参考此处的格式规范来做成的：https://github.com/Shadowsocks-NET/shadowsocks-specs/blob/main/2022-3-shadowsocks-url.md
至于ss我个人感觉没必要使用http伪装

**Comment by taffychan** [comment]
而且QV目前作者已经跑路，只能选择非ss2022的协议
